### ISSUE TITLE
Cannot just change mimetype with /rest/types/{id}

### ISSUE THREAD

**Issue by brambg** [knaw-huc/textrepo#83]
When trying to change the mimetype of a given type,
`/rest/types/{id}` requires both `name` and `mimetype`
If we use the original type name (since we don't want to change that), the `PUT` returns a `Duplicate type name` error

Suggested fix: The type.getName existence check for the `upsert` in `JdbiTypeService` should accept an existing typeName when the typeIds match.

**Comment by hayco** [comment]
Internal Jira TT-874
